"""Add additional user id field to audit

Revision ID: 0265e561cb38
Revises: a1fb34464cd5
Create Date: 2025-07-16 04:42:01.356947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0265e561cb38'
down_revision: Union[str, None] = 'a1fb34464cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'audits', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'audits', type_='foreignkey')
    op.drop_column('audits', 'user_id')
    # ### end Alembic commands ###
