"""Deconstruct location field

Revision ID: 1f954d554b7e
Revises: d032748641ab
Create Date: 2025-07-08 05:34:54.788388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1f954d554b7e'
down_revision: Union[str, None] = 'd032748641ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('branches', sa.Column('municipality', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('branches', sa.Column('barangay', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('branches', 'location')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branches', sa.Column('location', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('branches', 'barangay')
    op.drop_column('branches', 'municipality')
    op.drop_column('branches', 'province')
    # ### end Alembic commands ###
