"""Add expenses field to audit

Revision ID: 38e2ed10907c
Revises: 0265e561cb38
Create Date: 2025-07-20 16:59:50.734220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '38e2ed10907c'
down_revision: Union[str, None] = '0265e561cb38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('expenses', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('audits', 'expenses')
    # ### end Alembic commands ###
