"""Add additional fields to audit

Revision ID: a1fb34464cd5
Revises: 5813cf8b1db8
Create Date: 2025-07-16 04:38:17.726702

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a1fb34464cd5'
down_revision: Union[str, None] = '5813cf8b1db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audits', sa.Column('refill_amount', sa.Float(), nullable=True))
    op.add_column('audits', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('audits', 'remaining',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('audits', 'dispensed',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('audits', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('audits', 'sales',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audits', 'sales',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('audits', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('audits', 'dispensed',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('audits', 'remaining',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('audits', 'category')
    op.drop_column('audits', 'refill_amount')
    # ### end Alembic commands ###
