[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[supervisord]
nodaemon=true
logfile=/var/log/supervisord.log
logfile_maxbytes=50MB
logfile_backups=5
pidfile=/tmp/supervisord.pid

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[program:worker]
command=uv run rq worker-pool email notification scheduled -n 4
directory=/workspace/app/api
autostart=true
autorestart=true
stdout_logfile=/temp/logs/worker.log
stderr_logfile=/temp/logs/worker.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3


[program:cron]
command=uv run rq cron api.worker.cron
directory=/workspace/app/api
autostart=true
autorestart=true
stdout_logfile=/temp/logs/cron.log
stderr_logfile=/temp/logs/cron.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
stdout_logfile_backups=3
stderr_logfile_backups=3
