export const geodata: Record<string, Record<string, string[]>> = {
  Marinduque: {
    Boac: [
      "Agot",
      "Agumaymayan",
      "Amoingon",
      "Apitong",
      "Balagasan",
      "Balaring",
      "Balimbing",
      "Balogo",
      "Bamban",
      "Bangbangalon",
      "Bantad",
      "Bantay",
      "Bayuti",
      "Binunga",
      "Boi",
      "Boton",
      "Buliasnin",
      "Bunganay",
      "Caganhao",
      "Canat",
      "Catubugan",
      "Cawit",
      "Daig",
      "Daypay",
      "Duyay",
      "Hinapulan",
      "Ihatub",
      "Isok I",
      "Isok II",
      "Laylay",
      "Lupac",
      "Mahinhin",
      "Mainit",
      "Malbog",
      "Maligaya",
      "Malusak",
      "Mansiwat",
      "Mataas Na Bayan",
      "Maybo",
      "Mercado",
      "Murallon",
      "Ogbac",
      "Pawa",
      "Pili",
      "Poctoy",
      "Poras",
      "Putting Buhangin",
      "Puyog",
      "Sabong",
      "San Miguel",
      "Santol",
      "Sawi",
      "Tabi",
      "Tabigue",
      "Tagwak",
      "Tambunan",
      "Tampus",
      "Tanza",
      "Tugos",
      "Tumagabok",
      "Tumapon",
    ],
    Buenavista: [
      "Bagacay",
      "Bagtingon",
      "Barangay I",
      "Barangay II",
      "Barangay III",
      "Barangay IV",
      "Bicas-bicas",
      "Caigangan",
      "Daykitin",
      "Libas",
      "Lipata",
      "Malbog",
      "Sihi",
      "Timbo",
      "Tungib-Lipata",
      "Yook",
    ],
    Gasan: [
      "Antipolo",
      "Bachao Ibaba",
      "Bachao Ilaya",
      "Bacong-bacong",
      "Bahi",
      "Bangbang",
      "Banot",
      "Banuyo",
      "Barangay I",
      "Barangay II",
      "Barangay III",
      "Bognuyan",
      "Cabugao",
      "Dawis",
      "Dili",
      "Libtangin",
      "Mahunig",
      "Mangiliol",
      "Masiga",
      "Matandang Gasan",
      "Pangi",
      "Pinggan",
      "Tabionan",
      "Tapuyan",
      "Tabionan",
      "Tapuyan",
      "Tiguion",
    ],
    Mogpog: [
      "Anapog-sibucao",
      "Argao",
      "Balanacan",
      "Banto",
      "Bintakay",
      "Bocboc",
      "Butansapa",
      "Candahon",
      "Dulong Bayan",
      "Gitnang Bayan",
      "Guisian",
      "Hinadharan",
      "Hinanggayon",
      "Ino",
      "Janagdong",
      "Lamesa",
      "Laon",
      "Magapua",
      "Malanday",
      "Malayak",
      "Malusak",
      "Mampaitan",
      "Mangyan-mababad",
      "Market Site",
      "Mataas Na Bayan",
      "Mendez",
      "Nangka I",
      "Nangka II",
      "Paye",
      "Pili",
      "Puting Buhangin",
      "Sayao",
      "Silangan",
      "Sumangga",
      "Tarug",
      "Villa Mendez",
    ],
    "Santa Cruz": [
      "Alobo",
      "Angas",
      "Aturan",
      "Bagong Silang Pob.",
      "Baguidbirin",
      "Baliis",
      "Balogo",
      "Banahaw Pob.",
      "Bangcuangan",
      "Banogbog",
      "Biga",
      "Botilao",
      "Buyabod",
      "Dating Bayan",
      "Devilla",
      "Dolores",
      "Haguimit",
      "Hupi",
      "Ipil",
      "Jolo",
      "Kaganhao",
      "Kalangkang",
      "Kamandugan",
      "Kasily",
      "Kilo-kilo",
      "Kinyaman",
      "Labo",
      "Lamesa",
      "Landy",
      "Lapu-lapu",
      "Libjo",
      "Lipa",
      "Lusok",
      "Maharlika",
      "Makulapnit",
      "Maniwaya",
      "Maniwaya",
      "Manlibunan",
      "Masaguisi",
      "Masalukot",
      "Matalaba",
      "Mongpong",
      "Morales",
      "Napo ",
      "Pag-asa",
      "Pantayin",
      "Polo",
      "Pulong-Parang",
      "Punong",
      "San Antonio",
      "San Isidro",
      "Tagum",
      "Tamayo",
      "Tambangan",
      "Tawiran",
      "Taytay",
    ],
    Torrijos: [
      "Bangwayin",
      "Bayakbakin",
      "Bolo",
      "Bonliw",
      "Buangan",
      "Cabuyo",
      "Cagpo",
      "Dampulan",
      "Kay Duke",
      "Mabuhay",
      "Makawayan",
      "Malibago",
      "Malinao",
      "Maranlig",
      "Marlangga",
      "Matuyatuya",
      "Nangka",
      "Pakaskasan",
      "Payanas",
      "Poblacion",
      "Poctoy",
      "Sibuyao",
      "Suha",
      "Talawan",
      "Tigwi",
    ],
  },
};
